{{- if and .Values.basicAuth.enabled (not .Values.basicAuth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "names.fullname" . }}-htpasswd-file
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  auth: {{ include "tplvalues.render" ( dict "value" .Values.basicAuth.content "context" $ ) | b64enc | quote }}
{{- end }}
