{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "names.fullname" . }}
  namespace: {{ include "names.namespace" . | quote }}
  labels: {{- include "labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.drupalPassword }}
  drupal-password: {{ default "" .Values.drupalPassword | b64enc | quote }}
  {{- else }}
  drupal-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
{{- end }}
---
{{- if .Values.smtp }}
apiVersion: v1
kind: Secret
metadata:
  name: smtp
  namespace: {{ include "names.namespace" . | quote }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  username: ""
  password: ""
{{- end }}